name: flutter_client_app
description: "A real-time feature flag integration demo app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # This library lets Flutter open a live real-time connection to our Python server
  web_socket_channel: ^3.0.1 

dev_dependencies:
  flutter_test:
    sdk: flutter